//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DelloiteTR.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.OverseasServiceSoap")]
    public interface OverseasServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddOverseasIncome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddOverseasIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddAsset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddRental", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddRental(DelloiteTR.ServiceReference1.OverseasRental jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCapital", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void AddCapital(DelloiteTR.ServiceReference1.OverseasCapital jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditOverseasIncome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EditOverseasIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditAsset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EditAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditRental", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EditRental(DelloiteTR.ServiceReference1.OverseasRental jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditCapital", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void EditCapital(DelloiteTR.ServiceReference1.OverseasCapital jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrency", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetCurrency();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetExchange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetExchange(string currency, string type, string interval, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncomeBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetIncomeBy(int type, string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSummary", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetSummary(string TaxPlayerNumber, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSummary2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DelloiteTR.ServiceReference1.Summary[] GetSummary2(string TaxPlayerNumber, string country);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncomeByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetIncomeByCountry(int type, string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIrregularIncome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetIrregularIncome(string TaxPlayerNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAssetBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetAssetBy(int type, string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentalBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetRentalBy(int type, string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentalByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetRentalByCountry(int type, string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCapitalBy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetCapitalBy(string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCapitalByCountry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetCapitalByCountry(string TaxPlayerNumber, string form, string year);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteIncome", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAsset", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRental", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteRental(DelloiteTR.ServiceReference1.OverseasRental jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCapital", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteCapital(DelloiteTR.ServiceReference1.OverseasAsset jsonData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetIncomeByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetIncomeByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAssetByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetAssetByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetRentalByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetRentalByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCapitalByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetCapitalByID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDescription", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void GetDescription(string code);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OverseasIncome : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int typeField;
        
        private string taxPlayerNumberField;
        
        private string formField;
        
        private string yearField;
        
        private string countryField;
        
        private string currencyField;
        
        private string dateofreceiptField;
        
        private string intervalField;
        
        private string exchrateField;
        
        private string incomecurrencyField;
        
        private string taxpaidcurrencyField;
        
        private string incomerpField;
        
        private string taxpaidrpField;
        
        private string treatyrateField;
        
        private string ftcField;
        
        private string allowedftcField;
        
        private string irregularincomeField;
        
        private string createdbyField;
        
        private string createddateField;
        
        private string updatedbyField;
        
        private string updateddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxPlayerNumber {
            get {
                return this.taxPlayerNumberField;
            }
            set {
                this.taxPlayerNumberField = value;
                this.RaisePropertyChanged("TaxPlayerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
                this.RaisePropertyChanged("form");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string dateofreceipt {
            get {
                return this.dateofreceiptField;
            }
            set {
                this.dateofreceiptField = value;
                this.RaisePropertyChanged("dateofreceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string interval {
            get {
                return this.intervalField;
            }
            set {
                this.intervalField = value;
                this.RaisePropertyChanged("interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string exchrate {
            get {
                return this.exchrateField;
            }
            set {
                this.exchrateField = value;
                this.RaisePropertyChanged("exchrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string incomecurrency {
            get {
                return this.incomecurrencyField;
            }
            set {
                this.incomecurrencyField = value;
                this.RaisePropertyChanged("incomecurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string taxpaidcurrency {
            get {
                return this.taxpaidcurrencyField;
            }
            set {
                this.taxpaidcurrencyField = value;
                this.RaisePropertyChanged("taxpaidcurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string incomerp {
            get {
                return this.incomerpField;
            }
            set {
                this.incomerpField = value;
                this.RaisePropertyChanged("incomerp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string taxpaidrp {
            get {
                return this.taxpaidrpField;
            }
            set {
                this.taxpaidrpField = value;
                this.RaisePropertyChanged("taxpaidrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string treatyrate {
            get {
                return this.treatyrateField;
            }
            set {
                this.treatyrateField = value;
                this.RaisePropertyChanged("treatyrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string ftc {
            get {
                return this.ftcField;
            }
            set {
                this.ftcField = value;
                this.RaisePropertyChanged("ftc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string allowedftc {
            get {
                return this.allowedftcField;
            }
            set {
                this.allowedftcField = value;
                this.RaisePropertyChanged("allowedftc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string irregularincome {
            get {
                return this.irregularincomeField;
            }
            set {
                this.irregularincomeField = value;
                this.RaisePropertyChanged("irregularincome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string createdby {
            get {
                return this.createdbyField;
            }
            set {
                this.createdbyField = value;
                this.RaisePropertyChanged("createdby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string createddate {
            get {
                return this.createddateField;
            }
            set {
                this.createddateField = value;
                this.RaisePropertyChanged("createddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
                this.RaisePropertyChanged("updatedby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string updateddate {
            get {
                return this.updateddateField;
            }
            set {
                this.updateddateField = value;
                this.RaisePropertyChanged("updateddate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Summary : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryField;
        
        private string incomerp1Field;
        
        private string taxpaidrp1Field;
        
        private string incomecurrency1Field;
        
        private string taxpaidcurrency1Field;
        
        private string allowedftc1Field;
        
        private string incomerp2Field;
        
        private string taxpaidrp2Field;
        
        private string incomecurrency2Field;
        
        private string taxpaidcurrency2Field;
        
        private string allowedftc2Field;
        
        private string incomerp3Field;
        
        private string taxpaidrp3Field;
        
        private string incomecurrency3Field;
        
        private string taxpaidcurrency3Field;
        
        private string allowedftc3Field;
        
        private string cap_gainlossrpField;
        
        private string cap_taxpaidrpField;
        
        private string cap_gainlossField;
        
        private string cap_taxpaidField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string country {
            get {
                return this.countryField;
            }
            set {
                this.countryField = value;
                this.RaisePropertyChanged("country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string incomerp1 {
            get {
                return this.incomerp1Field;
            }
            set {
                this.incomerp1Field = value;
                this.RaisePropertyChanged("incomerp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string taxpaidrp1 {
            get {
                return this.taxpaidrp1Field;
            }
            set {
                this.taxpaidrp1Field = value;
                this.RaisePropertyChanged("taxpaidrp1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string incomecurrency1 {
            get {
                return this.incomecurrency1Field;
            }
            set {
                this.incomecurrency1Field = value;
                this.RaisePropertyChanged("incomecurrency1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string taxpaidcurrency1 {
            get {
                return this.taxpaidcurrency1Field;
            }
            set {
                this.taxpaidcurrency1Field = value;
                this.RaisePropertyChanged("taxpaidcurrency1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string allowedftc1 {
            get {
                return this.allowedftc1Field;
            }
            set {
                this.allowedftc1Field = value;
                this.RaisePropertyChanged("allowedftc1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string incomerp2 {
            get {
                return this.incomerp2Field;
            }
            set {
                this.incomerp2Field = value;
                this.RaisePropertyChanged("incomerp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string taxpaidrp2 {
            get {
                return this.taxpaidrp2Field;
            }
            set {
                this.taxpaidrp2Field = value;
                this.RaisePropertyChanged("taxpaidrp2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string incomecurrency2 {
            get {
                return this.incomecurrency2Field;
            }
            set {
                this.incomecurrency2Field = value;
                this.RaisePropertyChanged("incomecurrency2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string taxpaidcurrency2 {
            get {
                return this.taxpaidcurrency2Field;
            }
            set {
                this.taxpaidcurrency2Field = value;
                this.RaisePropertyChanged("taxpaidcurrency2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string allowedftc2 {
            get {
                return this.allowedftc2Field;
            }
            set {
                this.allowedftc2Field = value;
                this.RaisePropertyChanged("allowedftc2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string incomerp3 {
            get {
                return this.incomerp3Field;
            }
            set {
                this.incomerp3Field = value;
                this.RaisePropertyChanged("incomerp3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string taxpaidrp3 {
            get {
                return this.taxpaidrp3Field;
            }
            set {
                this.taxpaidrp3Field = value;
                this.RaisePropertyChanged("taxpaidrp3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string incomecurrency3 {
            get {
                return this.incomecurrency3Field;
            }
            set {
                this.incomecurrency3Field = value;
                this.RaisePropertyChanged("incomecurrency3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string taxpaidcurrency3 {
            get {
                return this.taxpaidcurrency3Field;
            }
            set {
                this.taxpaidcurrency3Field = value;
                this.RaisePropertyChanged("taxpaidcurrency3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string allowedftc3 {
            get {
                return this.allowedftc3Field;
            }
            set {
                this.allowedftc3Field = value;
                this.RaisePropertyChanged("allowedftc3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string cap_gainlossrp {
            get {
                return this.cap_gainlossrpField;
            }
            set {
                this.cap_gainlossrpField = value;
                this.RaisePropertyChanged("cap_gainlossrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string cap_taxpaidrp {
            get {
                return this.cap_taxpaidrpField;
            }
            set {
                this.cap_taxpaidrpField = value;
                this.RaisePropertyChanged("cap_taxpaidrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string cap_gainloss {
            get {
                return this.cap_gainlossField;
            }
            set {
                this.cap_gainlossField = value;
                this.RaisePropertyChanged("cap_gainloss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string cap_taxpaid {
            get {
                return this.cap_taxpaidField;
            }
            set {
                this.cap_taxpaidField = value;
                this.RaisePropertyChanged("cap_taxpaid");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OverseasCapital : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string taxPlayerNumberField;
        
        private string formField;
        
        private string yearField;
        
        private string cap_descriptionField;
        
        private string cap_countryField;
        
        private string cap_currencyField;
        
        private string cap_sellingdateField;
        
        private string cap_intervalField;
        
        private string cap_exchrateField;
        
        private string cap_proceedsField;
        
        private string cap_costField;
        
        private string cap_gainlossField;
        
        private string cap_taxpaidField;
        
        private string cap_gainlossrpField;
        
        private string cap_taxpaidrpField;
        
        private string cap_irregularincomeField;
        
        private string createdbyField;
        
        private string createddateField;
        
        private string updatedbyField;
        
        private string updateddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TaxPlayerNumber {
            get {
                return this.taxPlayerNumberField;
            }
            set {
                this.taxPlayerNumberField = value;
                this.RaisePropertyChanged("TaxPlayerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
                this.RaisePropertyChanged("form");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string cap_description {
            get {
                return this.cap_descriptionField;
            }
            set {
                this.cap_descriptionField = value;
                this.RaisePropertyChanged("cap_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string cap_country {
            get {
                return this.cap_countryField;
            }
            set {
                this.cap_countryField = value;
                this.RaisePropertyChanged("cap_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string cap_currency {
            get {
                return this.cap_currencyField;
            }
            set {
                this.cap_currencyField = value;
                this.RaisePropertyChanged("cap_currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string cap_sellingdate {
            get {
                return this.cap_sellingdateField;
            }
            set {
                this.cap_sellingdateField = value;
                this.RaisePropertyChanged("cap_sellingdate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string cap_interval {
            get {
                return this.cap_intervalField;
            }
            set {
                this.cap_intervalField = value;
                this.RaisePropertyChanged("cap_interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string cap_exchrate {
            get {
                return this.cap_exchrateField;
            }
            set {
                this.cap_exchrateField = value;
                this.RaisePropertyChanged("cap_exchrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string cap_proceeds {
            get {
                return this.cap_proceedsField;
            }
            set {
                this.cap_proceedsField = value;
                this.RaisePropertyChanged("cap_proceeds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string cap_cost {
            get {
                return this.cap_costField;
            }
            set {
                this.cap_costField = value;
                this.RaisePropertyChanged("cap_cost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string cap_gainloss {
            get {
                return this.cap_gainlossField;
            }
            set {
                this.cap_gainlossField = value;
                this.RaisePropertyChanged("cap_gainloss");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string cap_taxpaid {
            get {
                return this.cap_taxpaidField;
            }
            set {
                this.cap_taxpaidField = value;
                this.RaisePropertyChanged("cap_taxpaid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string cap_gainlossrp {
            get {
                return this.cap_gainlossrpField;
            }
            set {
                this.cap_gainlossrpField = value;
                this.RaisePropertyChanged("cap_gainlossrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string cap_taxpaidrp {
            get {
                return this.cap_taxpaidrpField;
            }
            set {
                this.cap_taxpaidrpField = value;
                this.RaisePropertyChanged("cap_taxpaidrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string cap_irregularincome {
            get {
                return this.cap_irregularincomeField;
            }
            set {
                this.cap_irregularincomeField = value;
                this.RaisePropertyChanged("cap_irregularincome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string createdby {
            get {
                return this.createdbyField;
            }
            set {
                this.createdbyField = value;
                this.RaisePropertyChanged("createdby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string createddate {
            get {
                return this.createddateField;
            }
            set {
                this.createddateField = value;
                this.RaisePropertyChanged("createddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
                this.RaisePropertyChanged("updatedby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string updateddate {
            get {
                return this.updateddateField;
            }
            set {
                this.updateddateField = value;
                this.RaisePropertyChanged("updateddate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OverseasRental : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int typeField;
        
        private string taxPlayerNumberField;
        
        private string formField;
        
        private string yearField;
        
        private string ren_informationField;
        
        private string ren_countryField;
        
        private string ren_currencyField;
        
        private string ren_dateofreceiptField;
        
        private string ren_intervalField;
        
        private string ren_exchrateField;
        
        private string ren_amountcurrencyField;
        
        private string ren_amountrpField;
        
        private string ren_irregularincomeField;
        
        private string createdbyField;
        
        private string createddateField;
        
        private string updatedbyField;
        
        private string updateddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxPlayerNumber {
            get {
                return this.taxPlayerNumberField;
            }
            set {
                this.taxPlayerNumberField = value;
                this.RaisePropertyChanged("TaxPlayerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
                this.RaisePropertyChanged("form");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ren_information {
            get {
                return this.ren_informationField;
            }
            set {
                this.ren_informationField = value;
                this.RaisePropertyChanged("ren_information");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ren_country {
            get {
                return this.ren_countryField;
            }
            set {
                this.ren_countryField = value;
                this.RaisePropertyChanged("ren_country");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ren_currency {
            get {
                return this.ren_currencyField;
            }
            set {
                this.ren_currencyField = value;
                this.RaisePropertyChanged("ren_currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string ren_dateofreceipt {
            get {
                return this.ren_dateofreceiptField;
            }
            set {
                this.ren_dateofreceiptField = value;
                this.RaisePropertyChanged("ren_dateofreceipt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string ren_interval {
            get {
                return this.ren_intervalField;
            }
            set {
                this.ren_intervalField = value;
                this.RaisePropertyChanged("ren_interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string ren_exchrate {
            get {
                return this.ren_exchrateField;
            }
            set {
                this.ren_exchrateField = value;
                this.RaisePropertyChanged("ren_exchrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ren_amountcurrency {
            get {
                return this.ren_amountcurrencyField;
            }
            set {
                this.ren_amountcurrencyField = value;
                this.RaisePropertyChanged("ren_amountcurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ren_amountrp {
            get {
                return this.ren_amountrpField;
            }
            set {
                this.ren_amountrpField = value;
                this.RaisePropertyChanged("ren_amountrp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string ren_irregularincome {
            get {
                return this.ren_irregularincomeField;
            }
            set {
                this.ren_irregularincomeField = value;
                this.RaisePropertyChanged("ren_irregularincome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string createdby {
            get {
                return this.createdbyField;
            }
            set {
                this.createdbyField = value;
                this.RaisePropertyChanged("createdby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string createddate {
            get {
                return this.createddateField;
            }
            set {
                this.createddateField = value;
                this.RaisePropertyChanged("createddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
                this.RaisePropertyChanged("updatedby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string updateddate {
            get {
                return this.updateddateField;
            }
            set {
                this.updateddateField = value;
                this.RaisePropertyChanged("updateddate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class OverseasAsset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private int typeField;
        
        private string taxPlayerNumberField;
        
        private string formField;
        
        private string yearField;
        
        private string as_descriptionField;
        
        private string as_refnumberField;
        
        private string as_detailsField;
        
        private string as_currencyField;
        
        private string as_balancedateField;
        
        private string as_intervalField;
        
        private string as_originalcurrencyField;
        
        private string as_exchrateField;
        
        private string as_inrupiahField;
        
        private string createdbyField;
        
        private string createddateField;
        
        private string updatedbyField;
        
        private string updateddateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string TaxPlayerNumber {
            get {
                return this.taxPlayerNumberField;
            }
            set {
                this.taxPlayerNumberField = value;
                this.RaisePropertyChanged("TaxPlayerNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string form {
            get {
                return this.formField;
            }
            set {
                this.formField = value;
                this.RaisePropertyChanged("form");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string as_description {
            get {
                return this.as_descriptionField;
            }
            set {
                this.as_descriptionField = value;
                this.RaisePropertyChanged("as_description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string as_refnumber {
            get {
                return this.as_refnumberField;
            }
            set {
                this.as_refnumberField = value;
                this.RaisePropertyChanged("as_refnumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string as_details {
            get {
                return this.as_detailsField;
            }
            set {
                this.as_detailsField = value;
                this.RaisePropertyChanged("as_details");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string as_currency {
            get {
                return this.as_currencyField;
            }
            set {
                this.as_currencyField = value;
                this.RaisePropertyChanged("as_currency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string as_balancedate {
            get {
                return this.as_balancedateField;
            }
            set {
                this.as_balancedateField = value;
                this.RaisePropertyChanged("as_balancedate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string as_interval {
            get {
                return this.as_intervalField;
            }
            set {
                this.as_intervalField = value;
                this.RaisePropertyChanged("as_interval");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string as_originalcurrency {
            get {
                return this.as_originalcurrencyField;
            }
            set {
                this.as_originalcurrencyField = value;
                this.RaisePropertyChanged("as_originalcurrency");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string as_exchrate {
            get {
                return this.as_exchrateField;
            }
            set {
                this.as_exchrateField = value;
                this.RaisePropertyChanged("as_exchrate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string as_inrupiah {
            get {
                return this.as_inrupiahField;
            }
            set {
                this.as_inrupiahField = value;
                this.RaisePropertyChanged("as_inrupiah");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string createdby {
            get {
                return this.createdbyField;
            }
            set {
                this.createdbyField = value;
                this.RaisePropertyChanged("createdby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string createddate {
            get {
                return this.createddateField;
            }
            set {
                this.createddateField = value;
                this.RaisePropertyChanged("createddate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string updatedby {
            get {
                return this.updatedbyField;
            }
            set {
                this.updatedbyField = value;
                this.RaisePropertyChanged("updatedby");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string updateddate {
            get {
                return this.updateddateField;
            }
            set {
                this.updateddateField = value;
                this.RaisePropertyChanged("updateddate");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OverseasServiceSoapChannel : DelloiteTR.ServiceReference1.OverseasServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OverseasServiceSoapClient : System.ServiceModel.ClientBase<DelloiteTR.ServiceReference1.OverseasServiceSoap>, DelloiteTR.ServiceReference1.OverseasServiceSoap {
        
        public OverseasServiceSoapClient() {
        }
        
        public OverseasServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OverseasServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OverseasServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OverseasServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public void AddOverseasIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData) {
            base.Channel.AddOverseasIncome(jsonData);
        }
        
        public void AddAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData) {
            base.Channel.AddAsset(jsonData);
        }
        
        public void AddRental(DelloiteTR.ServiceReference1.OverseasRental jsonData) {
            base.Channel.AddRental(jsonData);
        }
        
        public void AddCapital(DelloiteTR.ServiceReference1.OverseasCapital jsonData) {
            base.Channel.AddCapital(jsonData);
        }
        
        public void EditOverseasIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData) {
            base.Channel.EditOverseasIncome(jsonData);
        }
        
        public void EditAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData) {
            base.Channel.EditAsset(jsonData);
        }
        
        public void EditRental(DelloiteTR.ServiceReference1.OverseasRental jsonData) {
            base.Channel.EditRental(jsonData);
        }
        
        public void EditCapital(DelloiteTR.ServiceReference1.OverseasCapital jsonData) {
            base.Channel.EditCapital(jsonData);
        }
        
        public void GetCurrency() {
            base.Channel.GetCurrency();
        }
        
        public void GetExchange(string currency, string type, string interval, string year) {
            base.Channel.GetExchange(currency, type, interval, year);
        }
        
        public void GetIncomeBy(int type, string TaxPlayerNumber, string form, string year) {
            base.Channel.GetIncomeBy(type, TaxPlayerNumber, form, year);
        }
        
        public void GetSummary(string TaxPlayerNumber, string country) {
            base.Channel.GetSummary(TaxPlayerNumber, country);
        }
        
        public DelloiteTR.ServiceReference1.Summary[] GetSummary2(string TaxPlayerNumber, string country) {
            return base.Channel.GetSummary2(TaxPlayerNumber, country);
        }
        
        public void GetIncomeByCountry(int type, string TaxPlayerNumber, string form, string year) {
            base.Channel.GetIncomeByCountry(type, TaxPlayerNumber, form, year);
        }
        
        public void GetIrregularIncome(string TaxPlayerNumber) {
            base.Channel.GetIrregularIncome(TaxPlayerNumber);
        }
        
        public void GetAssetBy(int type, string TaxPlayerNumber, string form, string year) {
            base.Channel.GetAssetBy(type, TaxPlayerNumber, form, year);
        }
        
        public void GetRentalBy(int type, string TaxPlayerNumber, string form, string year) {
            base.Channel.GetRentalBy(type, TaxPlayerNumber, form, year);
        }
        
        public void GetRentalByCountry(int type, string TaxPlayerNumber, string form, string year) {
            base.Channel.GetRentalByCountry(type, TaxPlayerNumber, form, year);
        }
        
        public void GetCapitalBy(string TaxPlayerNumber, string form, string year) {
            base.Channel.GetCapitalBy(TaxPlayerNumber, form, year);
        }
        
        public void GetCapitalByCountry(string TaxPlayerNumber, string form, string year) {
            base.Channel.GetCapitalByCountry(TaxPlayerNumber, form, year);
        }
        
        public void DeleteIncome(DelloiteTR.ServiceReference1.OverseasIncome jsonData) {
            base.Channel.DeleteIncome(jsonData);
        }
        
        public void DeleteAsset(DelloiteTR.ServiceReference1.OverseasAsset jsonData) {
            base.Channel.DeleteAsset(jsonData);
        }
        
        public void DeleteRental(DelloiteTR.ServiceReference1.OverseasRental jsonData) {
            base.Channel.DeleteRental(jsonData);
        }
        
        public void DeleteCapital(DelloiteTR.ServiceReference1.OverseasAsset jsonData) {
            base.Channel.DeleteCapital(jsonData);
        }
        
        public void GetIncomeByID(int id) {
            base.Channel.GetIncomeByID(id);
        }
        
        public void GetAssetByID(int id) {
            base.Channel.GetAssetByID(id);
        }
        
        public void GetRentalByID(int id) {
            base.Channel.GetRentalByID(id);
        }
        
        public void GetCapitalByID(int id) {
            base.Channel.GetCapitalByID(id);
        }
        
        public void GetDescription(string code) {
            base.Channel.GetDescription(code);
        }
    }
}
