using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DelloiteTRLib.Model
{
    public class Calculation
    {
        public int id { get; set; }
        public string TaxPlayerNumber { get; set; }
        public string form { get; set; }
        public string year { get; set; }
        public int ammend { get; set; }

        public double? calc_rounded_b1 { get; set; }
        public double? calc_rounded_b2 { get; set; }
        public double? calc_rounded_b3 { get; set; }
        public double? calc_rounded_b4 { get; set; }
        public double? calc_rounded_b5 { get; set; }
        public double? calc_rounded_b6 { get; set; }
        public double? calc_rounded_b7 { get; set; }
        public double? calc_rounded_b8 { get; set; }
        public double? calc_not_b1 { get; set; }
        public double? calc_not_b2 { get; set; }
        public double? calc_not_b3 { get; set; }
        public double? calc_not_b4 { get; set; }
        public double? calc_not_b5 { get; set; }
        public double? calc_not_b6 { get; set; }
        public double? calc_not_b7 { get; set; }
        public double? calc_not_b8 { get; set; }
        public double? calc_not_b9 { get; set; }
        public double? calc_rounded_0 { get; set; }
        public double? calc_rounded_01 { get; set; }
        public double? calc_not_0 { get; set; }
        public double? calc_not_01 { get; set; }

        public double? calc_rounded_1 { get; set; }
        public double? calc_rounded_2 { get; set; }
        public double? calc_rounded_3 { get; set; }
        public double? calc_rounded_4 { get; set; }
        public double? calc_rounded_5 { get; set; }
        public double? calc_rounded_6 { get; set; }
        public double? calc_rounded_7 { get; set; }
        public double? calc_rounded_8 { get; set; }
        public double? calc_rounded_9 { get; set; }
        public double? calc_rounded_10 { get; set; }
        public double? calc_rounded_11 { get; set; }
        public double? calc_rounded_12 { get; set; }
        public double? calc_rounded_13 { get; set; }
        public double? calc_rounded_14 { get; set; }
        public double? calc_rounded_15 { get; set; }
        public double? calc_rounded_16 { get; set; }
        public double? calc_rounded_17 { get; set; }
        public double? calc_rounded_18 { get; set; }
        public double? calc_rounded_19 { get; set; }
        public double? calc_rounded_20 { get; set; }
        public double? calc_rounded_21 { get; set; }
        public double? calc_rounded_22 { get; set; }
        public double? calc_rounded_23 { get; set; }
        public double? calc_rounded_24 { get; set; }
        public double? calc_rounded_25 { get; set; }
        public double? calc_rounded_26 { get; set; }
        public double? calc_rounded_27 { get; set; }
        public double? calc_rounded_28 { get; set; }
        public double? calc_rounded_29 { get; set; }
        public double? calc_rounded_30 { get; set; }
        public double? calc_rounded_31 { get; set; }
        public double? calc_rounded_32 { get; set; }
        public double? calc_rounded_33 { get; set; }
        public double? calc_rounded_34 { get; set; }
        public double? calc_rounded_35 { get; set; }
        public double? calc_rounded_36 { get; set; }
        public double? calc_rounded_37 { get; set; }
        public double? calc_rounded_38 { get; set; }
        public double? calc_rounded_39 { get; set; }
        public double? calc_rounded_40 { get; set; }
        public double? calc_rounded_41 { get; set; }
        public double? calc_rounded_42 { get; set; }
        public double? calc_rounded_43 { get; set; }
        public double? calc_rounded_44 { get; set; }
        public double? calc_rounded_45 { get; set; }
        public double? calc_rounded_46 { get; set; }
        public double? calc_rounded_47 { get; set; }
        public double? calc_rounded_48 { get; set; }
        public double? calc_rounded_49 { get; set; }
        public double? calc_rounded_50 { get; set; }
        public double? calc_rounded_51 { get; set; }
        public double? calc_rounded_52 { get; set; }
        public double? calc_rounded_53 { get; set; }
        public double? calc_rounded_54 { get; set; }
        public double? calc_rounded_55 { get; set; }
        public double? calc_rounded_56 { get; set; }
        public double? calc_rounded_57 { get; set; }
        public double? calc_rounded_58 { get; set; }
        public double? calc_rounded_59 { get; set; }
        public double? calc_rounded_60 { get; set; }
        public double? calc_rounded_61 { get; set; }
        public double? calc_rounded_62 { get; set; }
        public double? calc_rounded_63 { get; set; }
        public double? calc_rounded_64 { get; set; }
        public double? calc_rounded_65 { get; set; }
        public double? calc_rounded_66 { get; set; }
        public double? calc_rounded_67 { get; set; }
        public double? calc_rounded_68 { get; set; }
        public double? calc_rounded_69 { get; set; }
        public double? calc_rounded_70 { get; set; }
        public double? calc_rounded_71 { get; set; }
        public double? calc_rounded_72 { get; set; }
        public double? calc_rounded_73 { get; set; }
        public double? calc_not_1 { get; set; }
        public double? calc_not_2 { get; set; }
        public double? calc_not_3 { get; set; }
        public double? calc_not_4 { get; set; }
        public double? calc_not_5 { get; set; }
        public double? calc_not_6 { get; set; }
        public double? calc_not_7 { get; set; }
        public double? calc_not_8 { get; set; }
        public double? calc_not_9 { get; set; }
        public double? calc_not_10 { get; set; }
        public double? calc_not_11 { get; set; }
        public double? calc_not_12 { get; set; }
        public double? calc_not_13 { get; set; }
        public double? calc_not_14 { get; set; }
        public double? calc_not_15 { get; set; }
        public double? calc_not_16 { get; set; }
        public double? calc_not_17 { get; set; }
        public double? calc_not_18 { get; set; }
        public double? calc_not_19 { get; set; }
        public double? calc_not_20 { get; set; }
        public double? calc_not_21 { get; set; }
        public double? calc_not_22 { get; set; }
        public double? calc_not_23 { get; set; }
        public double? calc_not_24 { get; set; }
        public double? calc_not_25 { get; set; }
        public double? calc_not_26 { get; set; }
        public double? calc_not_27 { get; set; }
        public double? calc_not_28 { get; set; }
        public double? calc_not_29 { get; set; }
        public double? calc_not_30 { get; set; }
        public double? calc_not_31 { get; set; }
        public double? calc_not_32 { get; set; }
        public double? calc_not_33 { get; set; }
        public double? calc_not_34 { get; set; }
        public double? calc_not_35 { get; set; }
        public double? calc_not_36 { get; set; }
        public double? calc_not_37 { get; set; }
        public double? calc_not_38 { get; set; }
        public double? calc_not_39 { get; set; }
        public double? calc_not_40 { get; set; }
        public double? calc_not_41 { get; set; }
        public double? calc_not_42 { get; set; }
        public double? calc_not_43 { get; set; }
        public double? calc_not_44 { get; set; }
        public double? calc_not_45 { get; set; }
        public double? calc_not_46 { get; set; }
        public double? calc_not_47 { get; set; }
        public double? calc_not_48 { get; set; }
        public double? calc_not_49 { get; set; }
        public double? calc_not_50 { get; set; }
        public double? calc_not_51 { get; set; }
        public double? calc_not_52 { get; set; }
        public double? calc_not_53 { get; set; }
        public double? calc_not_54 { get; set; }
        public double? calc_not_55 { get; set; }
        public double? calc_not_56 { get; set; }
        public double? calc_not_57 { get; set; }
        public double? calc_not_58 { get; set; }
        public double? calc_not_59 { get; set; }
        public double? calc_not_60 { get; set; }
        public double? calc_not_61 { get; set; }
        public double? calc_not_62 { get; set; }
        public double? calc_not_63 { get; set; }
        public double? calc_not_64 { get; set; }
        public double? calc_not_65 { get; set; }
        public double? calc_not_66 { get; set; }
        public double? calc_not_67 { get; set; }
        public double? calc_not_68 { get; set; }
        public double? calc_not_69 { get; set; }
        public double? calc_not_70 { get; set; }
        public double? calc_not_71 { get; set; }
        public double? calc_not_72 { get; set; }
        public double? calc_not_73 { get; set; }
        public string createdby { get; set; }
        public string createddate { get; set; }
        public string updatedby { get; set; }
        public string updateddate { get; set; }
    }
}
