using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DelloiteTRLib.Model
{
    public class TaxForm
    {
        public string TaxPayerNumber { get; set; }

        public int id { get; set; }
        public int ammend { get; set; }
        public int status { get; set; }
        public string taxidnumber { get; set; }
        public string type { get; set; }
        public string year { get; set; }

        public string t1s1f2 { get; set; }
        public string t1s1f4 { get; set; }
        public string t1s1f5 { get; set; }
        public string t1s1f6 { get; set; }
        public string t1s1f7 { get; set; }
        public string t1s1f8 { get; set; }
        public string t1s2f1 { get; set; }
        public string t1s2f2 { get; set; }
        public string t1s2f3 { get; set; }
        public string t1s2f4 { get; set; }
        public string t1s2f5 { get; set; }
        public string t1s2f6 { get; set; }
        public string t1s2f7 { get; set; }
        public string t1s2f8 { get; set; }
        public string t1s2f9 { get; set; }
        public string t1s2f10 { get; set; }
        public string t1s2f11 { get; set; }
        public string t1s2f12 { get; set; }
        public string t1s2f13 { get; set; }
        public string t1s2f14 { get; set; }
        public string t1s2f15 { get; set; }
        public string t1s2f16 { get; set; }
        public string t1s2f17 { get; set; }
        public string t1s2f18 { get; set; }
        public string t1s2f19 { get; set; }
        public string t1s2f20 { get; set; }
        public string t1s2f21 { get; set; }
        public string t1s2f22 { get; set; }
        public string t1s2f23 { get; set; }
        public string t1s2f24 { get; set; }
        public string t1s3f1 { get; set; }
        public string t1s3f2 { get; set; }
        public string t1s3f3 { get; set; }
        public string t1s4f1 { get; set; }
        public string t1s4f2 { get; set; }
        public string t1s4f3 { get; set; }
        public string t1s4f4 { get; set; }
        public string t1s4f5 { get; set; }
        public string t1s4f6 { get; set; }
        public string t1s4f7 { get; set; }
        public string t1s4f8 { get; set; }
        public string t1s4f9 { get; set; }
        public string t1s4f10 { get; set; }
        public string t1s4f11 { get; set; }
        public string t1s4f12 { get; set; }
        public string t1s4f13 { get; set; }
        public string t1s4f14 { get; set; }
        public string t1s4f15 { get; set; }
        public string t1s4f16 { get; set; }
        public string t1s4f17 { get; set; }
        public string t1s4f18 { get; set; }
        public string t1s4f19 { get; set; }
        public string t1s4f20 { get; set; }
        public string t1s4f21 { get; set; }
        public string t1s4f22 { get; set; }
        public string t1s4f23 { get; set; }
        public string t1s4f24 { get; set; }
        public string t1s4f25 { get; set; }
        public string t1s4f26 { get; set; }
        public string t1s4f27 { get; set; }
        public string t1s4f28 { get; set; }
        public string t1s4f29 { get; set; }
        public string t1s4f30 { get; set; }
        public string t1s4f31 { get; set; }
        public string t1s4f32 { get; set; }
        public string t1s4f33 { get; set; }
        public string t1s4f34 { get; set; }
        public string t1s4f35 { get; set; }
        public string t1s4f36 { get; set; }
        public string t1s4f37 { get; set; }
        public string t1s4f38 { get; set; }
        public string t1s4f39 { get; set; }
        public string t1s4f40 { get; set; }
        public string t1s4f41 { get; set; }
        public string t1s4f42 { get; set; }
        public string t1s4f43 { get; set; }
        public string t1s4f44 { get; set; }
        public string t1s4f45 { get; set; }
        public string t1s4f46 { get; set; }
        public string t1s4f47 { get; set; }
        public string t1s4f48 { get; set; }
        public string t1s4f49 { get; set; }
        public string t1s4f50 { get; set; }
        public string t1s4f51 { get; set; }
        public string t1s4f52 { get; set; }
        public string t1s4f53 { get; set; }
        public string t1s4f54 { get; set; }
        public string t1s4f55 { get; set; }
        public string t1s6f1 { get; set; }
        public string t1s6f2 { get; set; }
        public string t1s6f3 { get; set; }
        public string t1s6f4 { get; set; }
        public string t1s6f5 { get; set; }
        public string t1s6f6 { get; set; }
        public string t1s6f7 { get; set; }
        public string t1s6f8 { get; set; }
        public string t1s6f9 { get; set; }
        public string t1s6f10 { get; set; }
        public string t1s6f11 { get; set; }
        public string t1s6f12 { get; set; }
        public string t1s6f13 { get; set; }
        public string t1s6f14 { get; set; }
        public string t1s6f15 { get; set; }
        public string t1s6f16 { get; set; }
        public string t1s6f17 { get; set; }
        public string t1s6f18 { get; set; }
        public string t1s6f19 { get; set; }
        public string t1s6f20 { get; set; }
        public string t1s6f21 { get; set; }
        public string t1s6f22 { get; set; }
        public string t1s6f23 { get; set; }
        public string t1s6f24 { get; set; }
        public string t1s6f25 { get; set; }
        public string t1s7f1 { get; set; }
        public string t1s7f2 { get; set; }
        public string t1s7f3 { get; set; }
        public string t1s7f4 { get; set; }
        public string t1s7f5 { get; set; }
        public string t1s7f6 { get; set; }
        public string t1s7f7 { get; set; }
        public string t1s7f8 { get; set; }
        public string t1s7f9 { get; set; }
        public string t1s7f10 { get; set; }
        public string t1s7f11 { get; set; }
        public string t1s7f12 { get; set; }
        public string t1s7f13 { get; set; }
        public string t1s7f14 { get; set; }
        public string t1s7f15 { get; set; }
        public string t1s7f16 { get; set; }
        public string t1s7f17 { get; set; }
        public string t1s7f18 { get; set; }
        public string t1s7f19 { get; set; }
        public string t1s7f20 { get; set; }
        public string t1s7f21 { get; set; }
        public string t1s7f22 { get; set; }
        public string t1s7f23 { get; set; }
        public string t1s7f24 { get; set; }
        public string t1s7f25 { get; set; }
        public string t1s7f26 { get; set; }
        public string t1s7f27 { get; set; }
        public string t1s7f28 { get; set; }
        public string t1s7f29 { get; set; }
        public string t1s7f30 { get; set; }
        public string t1s7f31 { get; set; }
        public string t1s7f32 { get; set; }
        public string t1s7f33 { get; set; }
        public string t1s7f34 { get; set; }
        public string t1s7f35 { get; set; }
        public string t1s7f36 { get; set; }
        public string t1s7f37 { get; set; }
        public string t1s7f38 { get; set; }
        public string t1s7f39 { get; set; }
        public string t1s8f1 { get; set; }
        public string t1s8f2 { get; set; }
        public string t1s8f3 { get; set; }
        public string t1s8f4 { get; set; }
        public string t1s8f5 { get; set; }
        public string t1s8f6 { get; set; }
        public string t1s8f7 { get; set; }
        public string t1s8f8 { get; set; }
        public string t1s8f9 { get; set; }
        public string t1s8f10 { get; set; }
        public string t1s8f11 { get; set; }
        public string t1s8f12 { get; set; }
        public string t1s8f13 { get; set; }
        public string t1s8f14 { get; set; }
        public string t1s8f15 { get; set; }
        public string t1s8f16 { get; set; }
        public string t1s8f17 { get; set; }
        public string t1s8f18 { get; set; }
        public string t1s8f19 { get; set; }
        public string t1s8f20 { get; set; }
        public string t1s8f21 { get; set; }
        public string t1s8f22 { get; set; }
        public string t1s8f23 { get; set; }
        public string t1s8f24 { get; set; }
        public string t1s8f25 { get; set; }
        public string t1s8f26 { get; set; }
        public string t1s8f27 { get; set; }
        public string t1s8f28 { get; set; }
        public string t1s8f29 { get; set; }
        public string t1s8f30 { get; set; }
        public string t1s8f31 { get; set; }
        public string t1s8f32 { get; set; }
        public string t1s8f33 { get; set; }
        public string t1s8f34 { get; set; }
        public string t1s8f35 { get; set; }
        public string t1s8f36 { get; set; }
        public string t1s8f37 { get; set; }
        public string t1s8f38 { get; set; }
        public string t1s8f39 { get; set; }
        public string t1s8f40 { get; set; }
        public string t1s8f41 { get; set; }
        public string t1s8f42 { get; set; }
        public string t1s8f43 { get; set; }

        public string totalemployee { get; set; }
        public string totalperiod { get; set; }
        public string totalsalaries { get; set; }
        public string totalincome { get; set; }
        public string totalother { get; set; }
        public string totalhonorarium { get; set; }
        public string totalinsurance { get; set; }
        public string totalbenefit { get; set; }
        public string totalbonus { get; set; }
        public string totalgross { get; set; }
        public string totalcost { get; set; }
        public string totalpension { get; set; }
        public string totalpensioncost { get; set; }
        public string totalincome25 { get; set; }
        public string totalincome26 { get; set; }
        public string totalincome27 { get; set; }
        public string totalincome28 { get; set; }
        public string totalincome29 { get; set; }
        public string totaldeductions { get; set; }
        public string totalnetincome { get; set; }
        public string totalincometax { get; set; }
        public string totalprevnetincome { get; set; }
        public string totalprevincometax { get; set; }
        public string total1 { get; set; }
        public string total2 { get; set; }
        public string total3 { get; set; }
        public string total4 { get; set; }
        public string total5 { get; set; }
        public string total6 { get; set; }
        public string total7 { get; set; }
        public string total8 { get; set; }
        public string total9 { get; set; }
        public string total10 { get; set; }
        public string total11 { get; set; }
        public string total12 { get; set; }
        public string total13 { get; set; }
        public string total14 { get; set; }
        public string total15 { get; set; }
        public string total16 { get; set; }
        public string total17 { get; set; }
        public string total18 { get; set; }
        public string total19 { get; set; }
        public string total20 { get; set; }
        public string total21 { get; set; }
        public string total22 { get; set; }
        public string total23 { get; set; }
        public string total24 { get; set; }
        public string total25 { get; set; }
        public string total26 { get; set; }

        public string ren_netamountcurrency { get; set; }
        public string ren_netamountrp { get; set; }
        public string ren_nettaxpaidcurrency { get; set; }
        public string ren_nettaxpaidexchrate { get; set; }
        public string ren_nettaxpaidamountrp { get; set; }
        public string tabirregulartotal1 { get; set; }
        public string tabirregulartotal2 { get; set; }
        public string irregulartaxcredit { get; set; }
        public string lbltotalsummary1 { get; set; }
        public string lbltotalsummary2 { get; set; }


        public string tabasset1 { get; set; }
        public string tabasset2 { get; set; }
        public string tabasset3 { get; set; }
        public string tabasset4 { get; set; }
        public string tabasset5 { get; set; }
        public string tabasset6 { get; set; }
        public string tabasset10 { get; set; }
        public string tab3nettotalasset { get; set; }
        public string tab3nettotalliabilities { get; set; }
        public string tab3netasset { get; set; }

        public string netincomeroundedyes { get; set; }
        public string bonusroundedyes { get; set; }
        public string totalperiodroundedyes { get; set; }

        public string netincomeroundednot { get; set; }
        public string bonusroundednot { get; set; }
        public string totalperiodroundednot { get; set; }

        public string createdby { get; set; }
        public string createddate { get; set; }
        public string updatedby { get; set; }
        public string updateddate { get; set; }


    }
}
